config/routes.rb
Promobug::Application.routes.draw do
  resources :schedules

  resources :offers

  resources :agendas

  resources :interests

  devise_for :users

  root :to => "home#index"

  get 'google_login' =>             'home#google_login'
  get 'google_login_response' =>    'home#google_login_response'
  get 'list_google_agendas' =>      'home#list_google_agendas'
  get 'check_new_offers' =>         'home#check_new_offers'

  post 'agendas/inactivate/:id' =>   'agendas#inactivate'
  post 'google_agenda/create_google_agenda' => 'agendas#create_google_agenda'

  namespace :api do
    post "user/login" =>              "users#login"
    post "user/sign_up" =>            "users#sign_up"
    post "interests/new" =>           "interests#new"
    get  "interests/get/:id" =>       "interests#get"
    get "interests/list" =>          "interests#list"
  end

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :interest
  belongs_to :offer

  def self.insert(offer, interest)
  	schedule = Schedule.new(:offer_id=>offer.id, :interest_id=>interest.id)
  	schedule.save
	
	puts "CREATE ON GOOGLE CALENDAR"
	agenda = interest.agenda
	user = agenda.user
	
	user.check_token_expiration
	user = agenda.user
	
	GoogleCalendar.create_event(user.access_token, offer, agenda)
	puts "SCHEDULING'S END"
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  # GET /schedules
  # GET /schedules.xml
  def index
    user = current_user
    
    # treat this a better way later
    unless user.email == "guicruz.zs@gmail.com"
      @schedules = Schedule.joins("INNER JOIN interests ON interests.id = schedules.interest_id 
                                   INNER JOIN agendas ON agendas.id = interests.agenda_id AND agendas.user_id = #{user.id}").order('schedules.created_at DESC')
    else
      @schedules = Schedule.order('schedules.created_at DESC')
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @schedules }
    end
  end

  # GET /schedules/1
  # GET /schedules/1.xml
  def show
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @schedule }
    end
  end

  # GET /schedules/new
  # GET /schedules/new.xml
  def new
    @schedule = Schedule.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @schedule }
    end
  end

  # GET /schedules/1/edit
  def edit
    @schedule = Schedule.find(params[:id])
  end

  # POST /schedules
  # POST /schedules.xml
  def create
    @schedule = Schedule.new(params[:schedule])

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to(@schedule, :notice => 'Schedule was successfully created.') }
        format.xml  { render :xml => @schedule, :status => :created, :location => @schedule }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /schedules/1
  # PUT /schedules/1.xml
  def update
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      if @schedule.update_attributes(params[:schedule])
        format.html { redirect_to(@schedule, :notice => 'Schedule was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.xml
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to(schedules_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :agenda_id %><br />
    <%= f.text_field :agenda_id %>
  </div>
  <div class="field">
    <%= f.label :offer_id %><br />
    <%= f.text_field :offer_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<h1>Histórico de Alertas</h1>

<% unless @schedules.empty? %>
  <div class="index_list">  
    <table class="history_table">
      <tr>
        <th><div class="wanted">Desejado(s)</div></th>
        <th><div class="unwanted">Indesejado(s)</div></th>
        <th><div class="sale">Promoção</div></th>
        <th><div class="created_at">Criado Interesse em</div></th>
        <th><div class="agenda">Calendário</div></th>
        <th><div class="alerted_at">Alertado em</div></th>
      </tr>

    <% @schedules.each_with_index do |schedule, idx| %>
      <% interest = schedule.interest %>
      <% offer = schedule.offer %>
      <tr <%= 'class="odd_line"'.html_safe if !idx.odd? %>>
        <td><div class="wanted"><%= interest.wanted%></div></td>
        <td><div class="unwanted"><%= interest.unwanted%></div></td>
        <td><div class="sale"><%= link_to(offer.twitter_message.gsub(offer.link,""), offer.link)%></div></td>
        <td><div class="created_at"><%= l interest.created_at, :format=>:standart %></div></td>
        <td><div class="agenda"><%= interest.agenda.name %></div></td>
        <td><div class="alerted_at"><%= l schedule.created_at, :format=>:standart %></div></td>
      </tr>
    <% end %>
    </table>
  </div>
<% else %>
  <div class="empty_list">
    Histórico de notificações vazio
  </div>
<% end %>

app/views/schedules/new.html.erb
<h1>New schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Agenda:</b>
  <%= @schedule.agenda_id %>
</p>

<p>
  <b>Offer:</b>
  <%= @schedule.offer_id %>
</p>


<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>