config/routes.rb
Promobug::Application.routes.draw do
  resources :schedules

  resources :offers

  resources :agendas

  resources :interests

  devise_for :users

  root :to => "home#index"

  get 'google_login' =>             'home#google_login'
  get 'google_login_response' =>    'home#google_login_response'
  get 'list_google_agendas' =>      'home#list_google_agendas'
  get 'check_new_offers' =>         'home#check_new_offers'

  post 'agendas/inactivate/:id' =>   'agendas#inactivate'
  post 'google_agenda/create_google_agenda' => 'agendas#create_google_agenda'

  namespace :api do
    post "user/login" =>              "users#login"
    post "user/sign_up" =>            "users#sign_up"
    post "interests/new" =>           "interests#new"
    get  "interests/get/:id" =>       "interests#get"
    get "interests/list" =>          "interests#list"
  end

end

app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :agenda
  belongs_to :user
  has_many :schedules
  
  validate :fill_out_wishes
  before_save :load_regexp

  ACTIVE_STATUS = true
  INATCIVE_STATUS = false

  named_scope :active, :conditions=>{:status=> Interest::ACTIVE_STATUS}

  def inactivate
    self.status = Interest::INATCIVE_STATUS
    self.save
  end

  def self.test
    offer = Offer.find 19
    Interest.verify(offer)
    puts "FIM TESTE"
  end

  def self.verify(offer)
    offer.twitter_message.gsub!(offer.link, "")
  	puts "INTEREST.VERIFY"
  	puts offer.inspect

    interests = Interest.active

    interests.each do |interest|
      offer.verify_interest(interest)
    end
    puts "VERIFICATION'S END"
  end

  def fill_out_wishes
    puts "FILL OUT WISHES"
    if self.wanted_regexp.blank?
      errors.add(:filter, "É obrigatório o preenchimento ao menos do(s) Desejado(s)")
    end
  end

  def load_regexp
    puts "LOAD REGEXP"
  	if self.status == Interest::ACTIVE_STATUS
      self.wanted_regexp = "" if self.wanted_regexp.nil?
      self.unwanted_regexp = "" if self.unwanted_regexp.nil?
      self.wanted = self.wanted_regexp.gsub(",", ",\s")
      self.unwanted = self.unwanted_regexp.gsub(",", ",\s")
      load_wanted_wanted_regexp
    	load_unwanted_wanted_regexp
    end
  end

  def clear_to_form
    wanted = nil
    unwanted = nil
  end

private
  def load_wanted_wanted_regexp
    unless wanted_regexp.blank?
      self.wanted_regexp = convert_to_regexp(self.wanted_regexp)
    end
  end

  def load_unwanted_wanted_regexp
    unless unwanted_regexp.blank?
      self.unwanted_regexp = convert_to_regexp(self.unwanted_regexp)
    end
  end

  def convert_to_regexp(data)
    data = data.gsub(/\s/,"\\s")
    data = "\/#{data.gsub(",","|")}\/"
    data
  end
end

app/controllers/api/interests_controller.rb
class Api::InterestsController < Api::ApplicationController
	before_filter :authenticate
	def new
		interest = Interest.new(
			:user_id => @user.id,
			:wanted_regexp => params["wanted_regexp"],
			:unwanted_regexp => params["unwanted_regexp"],
			:status => Interest::ACTIVE_STATUS
		)

		if interest.save
			@user.interests.active.each do |user_active_interest|
				user_active_interest.inactivate if user_active_interest.id != interest.id
			end
			respond_to_api(parse_data(interest))
		else
			respond_to_api(interest)
		end
	end

	def get
		interest = Interest.where(
			:id => params["id"],
			:user_id => @user.id,
			:status => Interest::ACTIVE_STATUS
		).last

		if interest.nil?
			interest = Interest.new
			interest.errors.add(:id, I18n.translate("errors.messages.invalid"))
			respond_to_api(interest)
		else
			respond_to_api(parse_data(interest))
		end
	end

	def list
		data_response = []
		@user.interests.each do |interest|
			data_response << parse_data(interest)
		end
		respond_to_api(data_response)
	end

	private
	def parse_data(interest)
		{
			:user_id => interest.user_id,
			:wanted => interest.wanted,
			:unwanted => interest.unwanted,
			:wanted_regexp => interest.wanted_regexp,
			:unwanted_regexp => interest.unwanted_regexp,
			:status => interest.status
		}
	end
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  # GET /interests
  # GET /interests.xml
  def index
    @interests = Interest.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @interests }
    end
  end

  # GET /interests/1
  # GET /interests/1.xml
  def show
    @interest = Interest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @interest }
    end
  end

  # GET /interests/new
  # GET /interests/new.xml
  def new
    @interest = Interest.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @interest }
    end
  end

  # GET /interests/1/edit
  def edit
    @interest = Interest.find(params[:id])
  end

  # POST /interests
  # POST /interests.xml
  def create
    @interest = Interest.new(params[:interest])

    respond_to do |format|
      if @interest.save
        format.html { redirect_to(@interest, :notice => 'Interest was successfully created.') }
        format.xml  { render :xml => @interest, :status => :created, :location => @interest }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @interest.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /interests/1
  # PUT /interests/1.xml
  def update
    @interest = Interest.find(params[:id])

    respond_to do |format|
      if @interest.update_attributes(params[:interest])
        format.html { redirect_to(@interest, :notice => 'Interest was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @interest.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /interests/1
  # DELETE /interests/1.xml
  def destroy
    @interest = Interest.find(params[:id])
    @interest.destroy

    respond_to do |format|
      format.html { redirect_to(interests_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/views/interests/_form.html.erb
<div id="wanteds" class="field">
  <label>Desejado(s)</label><br />
  <%= f.text_field :wanted %>
</div>

<div style="clear:both;"></div>

<div id="unwanteds" class="field">
  <label>Indesejado(s)</label><br />
  <%= f.text_field :unwanted %>
</div>

<div style="clear:both;"></div>

<%= f.hidden_field :wanted_regexp %>
<%= f.hidden_field :unwanted_regexp %>

<%= f.hidden_field :status, :value=>1 %>

app/views/interests/edit.html.erb
<h1>Editing interest</h1>

<%= render 'form' %>

<%= link_to 'Show', @interest %> |
<%= link_to 'Back', interests_path %>

app/views/interests/index.html.erb
<h1>Listing interests</h1>

<table>
  <tr>
    <th>User</th>
    <th>Wanted</th>
    <th>Unwanted</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @interests.each do |interest| %>
  <tr>
    <td><%= interest.user_id %></td>
    <td><%= interest.wanted %></td>
    <td><%= interest.unwanted %></td>
    <td><%= interest.status %></td>
    <td><%= link_to 'Show', interest %></td>
    <td><%= link_to 'Edit', edit_interest_path(interest) %></td>
    <td><%= link_to 'Destroy', interest, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Interest', new_interest_path %>

app/views/interests/new.html.erb
<h1>New interest</h1>

<%= render 'form' %>

<%= link_to 'Back', interests_path %>

app/views/interests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @interest.user_id %>
</p>

<p>
  <b>Wanted:</b>
  <%= @interest.wanted %>
</p>

<p>
  <b>Unwanted:</b>
  <%= @interest.unwanted %>
</p>

<p>
  <b>Status:</b>
  <%= @interest.status %>
</p>


<%= link_to 'Edit', edit_interest_path(@interest) %> |
<%= link_to 'Back', interests_path %>