config/routes.rb
Promobug::Application.routes.draw do
  resources :schedules

  resources :offers

  resources :agendas

  resources :interests

  devise_for :users

  root :to => "home#index"

  get 'google_login' =>             'home#google_login'
  get 'google_login_response' =>    'home#google_login_response'
  get 'list_google_agendas' =>      'home#list_google_agendas'
  get 'check_new_offers' =>         'home#check_new_offers'

  post 'agendas/inactivate/:id' =>   'agendas#inactivate'
  post 'google_agenda/create_google_agenda' => 'agendas#create_google_agenda'

  namespace :api do
    post "user/login" =>              "users#login"
    post "user/sign_up" =>            "users#sign_up"
    post "interests/new" =>           "interests#new"
    get  "interests/get/:id" =>       "interests#get"
    get "interests/list" =>          "interests#list"
  end

end

app/models/agenda.rb
class Agenda < ActiveRecord::Base
  belongs_to :user
  has_one :interest
  
  STATUS_ATIVO = true
  STATUS_INATIVO = false

  accepts_nested_attributes_for :interest

  validates_presence_of :google_code

  def interest_attributes=(interest_attributes)
	  build_interest(interest_attributes)
  end

  def inactivate()
  	self.status = Agenda::STATUS_INATIVO
  	self.interest.inactivate if self.save
  end

  def inactivate_the_old
    agenda = Agenda.where(:user_id=>self.user_id, :status=>Agenda::STATUS_ATIVO).first
    agenda.inactivate unless agenda.nil? or agenda.id == self.id
  end

  def clear_to_form
    interest.clear_to_form
  end

  def self.create_google_agenda(user,name)
    GoogleCalendar.create_calendar(user.access_token, name)
    # {"kind"=>"calendar#calendar", "id"=>"4i0duieojvusci5sjdisnpp0k8@group.calendar.google.com", "summary"=>"Agenda Teste", "etag"=>"\"SaH0JPgxpZtQtKmztOIhZtDaAls/hvTted6vG_-iOf99UezkJIeL0Fo\""}
  end
end

app/controllers/agendas_controller.rb
class AgendasController < ApplicationController
  before_filter :load_google_agendas, :only=>[:new, :create]
  # GET /agendas
  # GET /agendas.xml
  def index
    @agendas = Agenda.where(:user_id=>current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @agendas }
    end
  end

  # GET /agendas/1
  # GET /agendas/1.xml
  def show
    @agenda = Agenda.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @agenda }
    end
  end

  # GET /agendas/new
  # GET /agendas/new.xml
  def new
    @agenda = Agenda.new
    
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /agendas/1/edit
  def edit
    @agenda = Agenda.find(params[:id])
  end

  # POST /agendas
  # POST /agendas.xml
  def create
    puts "-------- params"
    puts params.inspect
    @agenda = Agenda.new(params[:agenda])
    puts "--------  agenda"
    respond_to do |format|
      if @agenda.save
        @agenda.inactivate_the_old
        format.html { redirect_to({:action=>"index"}, :notice => 'Agenda was successfully created.') }
      else
        @data_response = GoogleCalendar.list_agendas(session[:access_token])
        puts @agenda.inspect
        @agenda.clear_to_form
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /agendas/1
  # PUT /agendas/1.xml
  def update
    @agenda = Agenda.find(params[:id])

    respond_to do |format|
      if @agenda.update_attributes(params[:agenda])
        format.html { redirect_to(@agenda, :notice => 'Agenda was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @agenda.errors, :status => :unprocessable_entity }
      end
    end
  end

  def inactivate
    user = current_user
    agenda = Agenda.where(:id=>params[:id]).first
    respond_to do |format|
      if !agenda.nil? and (user.id == agenda.user_id)
        agenda.inactivate
        puts "SUCCESS"
        format.html { redirect_to({:controller=>"agendas", :action=>"index"}, :notice => 'Filtro desativado com sucesso!')}
      else
        puts "FAIL"
        format.html { redirect_to({:controller=>"agendas", :action=>"index"}, :notice => 'Não foi possível desativar esse filtro!')}
      end
    end
  end
  # DELETE /agendas/1
  # DELETE /agendas/1.xml
  def destroy
    @agenda = Agenda.find(params[:id])
    @agenda.destroy

    respond_to do |format|
      format.html { redirect_to(agendas_url) }
      format.xml  { head :ok }
    end
  end

  def create_google_agenda
    puts params.inspect
    unless params[:agenda_name].empty?
      @data_response = Agenda.create_google_agenda(current_user, params[:agenda_name])
      
      load_google_agendas
      puts "olha o dado......"
      puts @data_response.inspect
      data = @data_response
      
      @data_response ={}
      @data_response[:success] = true
      @data_response[:data] = data
    else
      @data_response = {}
      @data_response[:error] = "O nome da agenda não pode estar em branco."
      @data_response[:success] = false
    end
  end

  private
  def load_google_agendas
    puts "------ ooooooooooooooooo"
    current_user.check_token_expiration
    @data_response = GoogleCalendar.list_agendas(current_user.access_token)
  end
end

app/helpers/agendas_helper.rb
module AgendasHelper
end

app/views/agendas/_form.html.erb
<%= form_for(@agenda) do |f| %>
  <% if @agenda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agenda.errors.count, "erro") %> não permitiram que esse filtro fosse salvo:</h2>

      <ul>
      <% @agenda.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, :value=>current_user.id %>
  <div id="ajax_message"></div>
  <div id= "agendas_box_list" class="field">
    <label>Agenda Google</label><br />
    <div class="agendas_form_list">
      <% @data_response["items"].each do |agenda|%>
        <div class="agenda_box">
          <%= f.radio_button :google_code, agenda["id"], :onclick=>"fill_name('#{agenda["summary"]}')" %>
          <div class="agenda_image" style="background-color:<%= agenda['backgroundColor']%>;"><%= image_tag "icon_calendar.png", :size=>"41x37" %></div>
          <div class="agenda_data">
            <%= agenda["summary"] %>
          </div>
        </div>
        <div style="clear:both;"></div>
      <% end %>
    </div>
  </div>
  <div id="create_agenda_box">
    <%= text_field_tag "calendar_name", nil, :size=>"30"%>
    <div class="button" style="width: 150px; float: left; line-height: 15px;">
      <div id="btn_create_google_agenda"> 
         Criar Nova Agenda
      </div>
    </div>
    <div style="clear:both"></div>
  </div>

  <%= f.hidden_field :name %>
  <%= f.hidden_field :status, :value=>1 %>

  <%= fields_for "agenda[interest_attributes]", @agenda.interest do |interest_form| %>
    <%= render :partial=>"interests/form", :locals=>{:f=>interest_form} %>
  <% end %>

  <div class="actions">
    <%= f.submit "Criar filtro" %>
  </div>
  <div style="clear:both;"></div>
<% end %>

app/views/agendas/create_google_agenda.js.erb
console.log("Rodando em ajax");
jQuery("#modal_div").dialog("close");

<% if @data_response[:success] %>
	content_new_list = "";
		<% @data_response[:data]["items"].each do |google_calendar| %>
		   content_new_list += '<div class="agenda_box">';
	       content_new_list += 		'<input name="agenda[google_code]" onclick="fill_name("<%= google_calendar["summary"] %>")" type="radio" value="<%= google_calendar["id"] %>">';
	       content_new_list += 		'<div class="agenda_image" style="background-color:<%= google_calendar["backgroundColor"] %>;"><img alt="Icon_calendar" height="37" src="/images/icon_calendar.png?1367961274" width="41"></div>';
	       content_new_list += 		'<div class="agenda_data">';
	       content_new_list += 			'<%= google_calendar["summary"] %>';
	       content_new_list += 		'</div>';
	       content_new_list += '</div>';
	       content_new_list += '<div style="clear:both;"></div>';
      <% end %>
      jQuery(".agendas_form_list").html(content_new_list);
      jQuery("#calendar_name").val("");
     console.log(content_new_list);
<% else %>
	alert("<%= @data_response[:error] %>");
<% end %>

app/views/agendas/edit.html.erb
<h1>Editing agenda</h1>

<%= render 'form' %>

<%= link_to 'Show', @agenda %> |
<%= link_to 'Back', agendas_path %>

app/views/agendas/index.html.erb
<h1>Filtros</h1>

<% unless @agendas.empty? %>
  <div class="index_list">  
    <table class="filter_table">
      <tr>
        <th>Agenda</th>
        <th>Status</th>
        <th>Criado em</th>
        <th>Desejado(s)</th>
        <th>Indesejado(s)</th>
        <th></th>
      </tr>

    <% @agendas.each_with_index do |agenda, idx| %>
      <% interest = agenda.interest %>
      <tr <%= 'class="odd_line"'.html_safe if !idx.odd? %>>
        <td><%= agenda.name %></td>
        <td><%= (agenda.status)? "<b>Ativo</b>".html_safe : "Inativo" %></td>
        <td><%= l(agenda.created_at, :format=>:long)%></td>
        <td><%= interest.wanted %></td>
        <td><%= interest.unwanted %></td>
        <td>
          <div class="inactivate_button">
              <%= link_to('Desativar', {:action=>"inactivate", :id=>agenda.id}, :confirm => 'Deseja inativar esse filtro?') if agenda.status %>
          </div>
        </td>
      </tr>
    <% end %>
    </table>
  </div>
<% else %>
  <div class="empty_list">
    Sem filtros Cadastrados
  </div>
<% end %>
</br>
<div class="button">
  <%= link_to 'Novo Filtro', new_agenda_path %>
</div>

app/views/agendas/new.html.erb
<%= javascript_include_tag "tag_box", "jquery-ui-1.10.4.custom.min" %>


<h1>Novo Filtro</h1>
<div class="filter_form">
	<div id="modal_div" style="display:none;"> </br> </br> Solicitando criação de agenda... <%= image_tag "ajax-loader.gif" %></div>
	<%= render 'form' %>
</div>
</br>	
<div class="button">
	<%= link_to 'Voltar', agendas_path, :id=>"btn_back" %>
</div>

app/views/agendas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @agenda.user_id %>
</p>

<p>
  <b>Google code:</b>
  <%= @agenda.google_code %>
</p>

<p>
  <b>Name:</b>
  <%= @agenda.name %>
</p>

<p>
  <b>Status:</b>
  <%= @agenda.status %>
</p>


<%= link_to 'Edit', edit_agenda_path(@agenda) %> |
<%= link_to 'Back', agendas_path %>