config/routes.rb
Promobug::Application.routes.draw do
  resources :schedules

  resources :offers

  resources :agendas

  resources :interests

  devise_for :users

  root :to => "home#index"

  get 'google_login' =>             'home#google_login'
  get 'google_login_response' =>    'home#google_login_response'
  get 'list_google_agendas' =>      'home#list_google_agendas'
  get 'check_new_offers' =>         'home#check_new_offers'

  post 'agendas/inactivate/:id' =>   'agendas#inactivate'
  post 'google_agenda/create_google_agenda' => 'agendas#create_google_agenda'

  namespace :api do
    post "user/login" =>              "users#login"
    post "user/sign_up" =>            "users#sign_up"
    post "interests/new" =>           "interests#new"
    get  "interests/get/:id" =>       "interests#get"
    get "interests/list" =>          "interests#list"
  end

end

app/models/offer.rb
class Offer < ActiveRecord::Base
	has_many :schedules

	def self.verify
		puts "RUNNING OFFER.VERIFY at #{Time.now.to_s}"
		logger.debug "RUNNING OFFER.VERIFY at #{Time.now.to_s}"
		promobug = Twitter.user("hardmob_promo")
		promobug_text = promobug.attrs[:status][:text]
		puts "PROMO => #{promobug_text}"
		logger.debug "PROMO => #{promobug_text}"
		last_offer = Offer.last
		if last_offer.nil? or last_offer.twitter_message != promobug_text
			offer = Offer.new_promobug(promobug)
			puts "SIGNED => #{offer.inspect}"
			logger.debug "SIGNED => #{offer.inspect}"
			Interest.verify(offer)
		end
	end

	def self.new_promobug(promobug)
		offer = Offer.new(:twitter_message=>promobug.attrs[:status][:text],
						  :link=>promobug.attrs[:status][:entities][:urls].first[:url])
		offer.save
		offer
	end

	def verify_interest(interest)
		puts "INTEREST ID #{interest.id} ANALYSIS"
		if is_wanted?(interest) and !is_unwanted?(interest)
			puts "CREATE SCHEDULE"
			schedule = Schedule.insert(self, interest)
		end
	end

	def is_wanted?(interest)
		if interest.wanted_regexp.empty? 
			return true
		end
		self.twitter_message.underscore.match(eval interest.wanted_regexp)
	end

	def is_unwanted?(interest)
		if interest.unwanted_regexp.empty? 
			return false
		end
		self.twitter_message.underscore.match(eval interest.unwanted_regexp)
	end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  # GET /offers
  # GET /offers.xml
  def index
    @offers = Offer.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @offers }
    end
  end

  # GET /offers/1
  # GET /offers/1.xml
  def show
    @offer = Offer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @offer }
    end
  end

  # GET /offers/new
  # GET /offers/new.xml
  def new
    @offer = Offer.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @offer }
    end
  end

  # GET /offers/1/edit
  def edit
    @offer = Offer.find(params[:id])
  end

  # POST /offers
  # POST /offers.xml
  def create
    @offer = Offer.new(params[:offer])

    respond_to do |format|
      if @offer.save
        format.html { redirect_to(@offer, :notice => 'Offer was successfully created.') }
        format.xml  { render :xml => @offer, :status => :created, :location => @offer }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @offer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /offers/1
  # PUT /offers/1.xml
  def update
    @offer = Offer.find(params[:id])

    respond_to do |format|
      if @offer.update_attributes(params[:offer])
        format.html { redirect_to(@offer, :notice => 'Offer was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @offer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.xml
  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy

    respond_to do |format|
      format.html { redirect_to(offers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= form_for(@offer) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :twitter_message %><br />
    <%= f.text_field :twitter_message %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<h1>Editing offer</h1>

<%= render 'form' %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.erb
<h1>Listing offers</h1>

<table>
  <tr>
    <th>Twitter message</th>
    <th>Link</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @offers.each do |offer| %>
  <tr>
    <td><%= offer.twitter_message %></td>
    <td><%= offer.link %></td>
    <td><%= link_to 'Show', offer %></td>
    <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
    <td><%= link_to 'Destroy', offer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Offer', new_offer_path %>

app/views/offers/new.html.erb
<h1>New offer</h1>

<%= render 'form' %>

<%= link_to 'Back', offers_path %>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Twitter message:</b>
  <%= @offer.twitter_message %>
</p>

<p>
  <b>Link:</b>
  <%= @offer.link %>
</p>


<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>